name: natural_computing
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pip
  - numba
  - jupyter_core
  - ipykernel
  - pip:
    - click
    - joblib
    - tqdm
    - matplotlib
    - orjson
    - deap
